inherit: 
    - wandb.yaml

training:
    task: linear_regression
    task_kwargs: {}
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000

out_dir: ../models/linear_regression

wandb:
    name: "linear_regression_standard"
